version: '2'

services:

    # Jury UI Service
    domserver: 
        image: daavar/domserver
        env_file: 
            - conf/mysql.conf
            - conf/domserver.conf
        links:
           - mysql
        network_mode: bridge
        restart: always

    # Judgehosts service
    judgehost: 
        image: daavar/judgehost
        env_file: conf/domserver.conf
        links:
           - domserver
        network_mode: bridge
        restart: always

    # Mysql database
    mysql:
       image: mariadb
       env_file: conf/mysql.conf
       volumes:
          - ./data/mysql:/var/lib/mysql 
       network_mode: bridge
       restart: always
    
    # Phpmyadmin
    phpmyadmin:
       image:  phpmyadmin/phpmyadmin
       env_file: conf/phpmyadmin.conf
       environment:
         -  UPLOAD_SIZE=1G
         -  PMA_HOST=mysql
       links:
         - mysql
       network_mode: bridge
       restart: always