#!/bin/bash

if [ ! $# -eq 0 ] ; then
    $@ 
    exit
fi

echo "dummy:$MYSQL_HOST:$MYSQL_DATABASE:$MYSQL_USER:$MYSQL_PASSWORD" >  /opt/domjudge/etc/dbpasswords.secret

echo "default $API_URL $API_USER $API_PASSWORD" > /opt/domjudge/etc/restapi.secret

chmod 777 -R /opt/domjudge/domserver/etc

[ -x /entrypoint ] && /entrypoint
